config/routes.rb
Bookshelf::Application.routes.draw do
  get "books/index"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :books
  root 'static_pages#home'
  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/users/:id/books', to: 'users#books', via: 'get', as: 'user_books'

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  validates :group_id, presence: true
  validates :title, presence: true
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :users
  has_many :books
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :group
  has_many :books

  before_save { email.downcase! }
  before_create :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }
  # validates :group_id, presence: true

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::MD5::hexdigest(token.to_s)
  end

  private
    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.where(group_id: current_user.group_id)
  end

  def new
    @book = current_user.group.books.build
  end

  def create
    @book = Book.new(book_params)
    # @book.group_id = current_user.group_id
    @book.update_attributes(
      group_id: current_user.group_id,
      user_id:  current_user.id
    )

    if @book.save
      flash[:success] = 'A new book added.'
      redirect_to user_books_path(current_user)
    else
      render 'new'
    end
  end

  private

  def book_params
    params.require(:book).permit(:title)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user,     only: [:edit, :update, :index]
  before_action :correct_user,       only: [:edit, :update]
  before_action :admin_user,         only: :destroy
  before_action :non_signed_in_user, only: [:new, :create]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @list_title = 'Borrowed Books'
    @user  = User.find(params[:id])
    @books = []
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = 'Welcome to the BookShelf!'
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id]).destroy
    if current_user?(user)
      redirect_to root_url
    else
      flash[:success] = 'User deleted.'
      redirect_to users_url
    end
  end

  def books
    @list_title = 'My Books'
    @user  = User.find(params[:id])
    @books = @user.books
    render 'show'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  # Befor filters
  def signed_in_user
    unless signed_in?
      store_location
      flash[:warning] = 'Please sign in.'
      redirect_to signin_url
    end
  end

  def non_signed_in_user
    redirect_to root_url if signed_in?
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return the full title on a per-page basis.
  def full_title(page_title)
    base_title = "BookShelf"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/books/_book.html.erb
<li>
  <%= gravatar_for book.user, size: 52 %>
  <%= book.title %>
</li>

app/views/books/_fields.html.erb
<%= render 'shared/book_error_messages' %>

<%= f.label :title, class: "control-label" %>
<%= f.text_field :title, class: "form-control" %>

app/views/books/index.html.erb
<% provide(:title, 'Books') %>
<h1><%= @books.first.group.name %>'s Books List</h1>

<ul class="books">
  <%= render @books %>
</ul>

app/views/books/new.html.erb
<% provide(:title, 'Add a book') %>
<h1>Add a book!</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@book) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Add a book", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    code <a href="https://github.com/toku345/bookshelf" target='_blank'>here</a> !!
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nabar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "BookShelf", root_path, id: "logo" %>
    </div><!-- /.navbar-header -->
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home", root_path %></li>
        <% if signed_in? %>
          <li><%= link_to "Books", books_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign out", signout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</header>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key,value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_book_error_messages.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@book.errors.count, "error") %>.
    </div>
    <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="jumbotron center">
  <h1>Welcome to the BookShelf</h1>

  <h2>
    This is a web-base book management system.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages' %>

<%= f.label :name, class: "control-label" %>
<%= f.text_field :name, class: "form-control" %>

<%= f.label :email, class: "control-label" %>
<%= f.text_field :email, class: "form-control" %>

<%= f.label :password, class: "control-label" %>
<%= f.password_field :password, class: "form-control" %>

<%= f.label :password_confirmation, "Confirm Password", class: "control-label" %>
<%= f.password_field :password_confirmation, class: "form-control" %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to 'delete', user, method: :delete, data: { cofirm: 'You sure?' } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <div class="under-the-button">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target='_blank'>changes</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-3">
    <section>
      <h1>
        <%= gravatar_for @user, size: 100 %>
        <%= @user.name %>
      </h1>
    </section>
    <div class="book-link-menu">
      <ul>
        <li><%= link_to 'Borrowed Books', user_path(@user) %></li>
        <li><%= link_to 'My Books', user_books_path(id: @user.id) %></li>
      </ul>
      <%= link_to 'Add a Book!', new_book_path, class: "btn btn-large btn-primary add-book-button" %>
    </div>
  </aside>
  <div class="col-md-9">
    <h3><%= @list_title %></h3>
    <ul class="books">
      <%= render @books %>
    </ul>
  </div>
</div>